from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fcc797055eac"
down_revision: str | None = "a7dcbe76d7c6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("config_ui", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "apply_privacy_zones_to_tracks",
                sa.Boolean(),
                server_default=sa.text("0"),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "apply_privacy_zones_to_heatmap",
                sa.Boolean(),
                server_default=sa.text("0"),
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("config_ui", schema=None) as batch_op:
        batch_op.drop_column("apply_privacy_zones_to_heatmap")
        batch_op.drop_column("apply_privacy_zones_to_tracks")

    # ### end Alembic commands ###
